<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Thank you guys!!!</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <script src="/static/js/jquery-2.1.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <div class="masthead">
        <H1>
            <a class="btn btn-large btn-lg pull-right" href="#" data-toggle="modal" data-target="#myModal">Поблагодарить</a>
            Благодарим за помощь

        </H1>
    </div>
    <br />
    <br />
<H2>Наиболее ценные события:</H2>
    <div class="row">
        <div class="span4">
            <b><?php echo $page["Best1"] ?></b>
        </div>
        <div class="span4">
            <b><?php echo $page["Best2"] ?></b>
        </div>
        <div class="span4">
            <b><?php echo $page["Best3"] ?></b>
        </div>
    </div>
    <HR>
<H3>Ну и их подвиг, конечно, тоже бессмертен, но чуть менее</H3>
<ul>
    <?php echo $page["others"];?>
</ul>
    <div class="footer">

    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 300px;">
        <div class="modal-content">
            <form role="form" action="index.html" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">И кто же у нас отличился?</h4>
                </div>
                <div class="modal-body">
                        <div class="form-group">
                            <select name="slave" id="slave" class="form-control">
                                <?php echo slavesOptions($db); ?>
                            </select> <br />,лично мне помог тем что
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="action" rows="4" placeholder="не мешал работать" ></textarea>
                        </div>
                        <input type="hidden" name="master" value="0">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Не важно</button>
                    <input type="submit" value="Рассказать" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>
